### ISSUE TITLE
The description for settings.clearTxAlert is for clearing not TX but address book

### ISSUE THREAD

**Issue by altbtm** [sugarchain-project/translation_android_wallet#37]
The description of the "settings.clearTxAlert" entry in th en.json goes;

`Remove all added addresses from the address book!`

However, according to its entry name "clearTxAlert", it should be something like;

`Remove all TX records!`

**Comment by decryp2kanon** [comment]
thats nice point. thanks!

**Comment by obasys** [comment]
@altbtm @decryp2kanon  Fixed it
