### ISSUE TITLE
Hard to read the white-colored descriptions because of the light gray background

### ISSUE THREAD

**Issue by altbtm** [sugarchain-project/translation_android_wallet#38]
For example, on the "Details of transaction" page, the descriptions are colored white and it makes it hard to read them because of the light gray background color. 

Why don't you color it darker?

![android_wallet_gray_background jpg](https://user-images.githubusercontent.com/60621506/73903721-27bea800-48dd-11ea-8ad0-b9cf8bbf6522.png)

**Comment by decryp2kanon** [comment]
yeah, it should be fixed in next release

**Comment by obasys** [comment]
@altbtm @decryp2kanon fixed
