### ISSUE TITLE
address linebreaking + white font

### ISSUE THREAD

**Issue by decryp2kanon** [sugarchain-project/translation_android_wallet#42]
![image](https://user-images.githubusercontent.com/60179867/73990821-a4a95a80-498d-11ea-926a-a0b380b9575d.png)

it displayed after succesful received.

white font: hard to read
address linebreaking

`sugar1qm78prm0pzag8tt2yunn703hhah5aq6s96cvxsu`

but

`sugar1qm78prm0pzag8tt2yunn703hhah5aq6s96c` LINEBREAK
`vxsu`

**Comment by obasys** [comment]
@decryp2kanon Fixed
