### ISSUE TITLE
wrong TX URL

### ISSUE THREAD

**Issue by decryp2kanon** [sugarchain-project/translation_android_wallet#45]
https://sugarchain.org/explorer/tx/12675df26be47de9f6fff9a4dc776cd4d0cd68fa2d5959e04ad7a5336c92f91e

is wrong

https://sugarchain.org/explorer/#/transaction/12675df26be47de9f6fff9a4dc776cd4d0cd68fa2d5959e04ad7a5336c92f91e

**Comment by obasys** [comment]
Fixed that
