### ISSUE TITLE
Error description fix

### ISSUE THREAD

**Issue by decryp2kanon** [sugarchain-project/translation_android_wallet#46]
![image](https://user-images.githubusercontent.com/60179867/73996291-99aaf600-499e-11ea-9e6b-aae9918e2c5d.png)

balance 0.00002

send 0.00001
fee 0.00001

**Comment by decryp2kanon** [comment]
DUST
![image](https://user-images.githubusercontent.com/60179867/73996472-058d5e80-499f-11ea-97f5-aba0ebbc928b.png)

**Comment by decryp2kanon** [comment]
same
![image](https://user-images.githubusercontent.com/60179867/73996488-0e7e3000-499f-11ea-8c85-9c17e844f6e4.png)

**Comment by obasys** [comment]
Also reviewed and fixed

**Comment by decryp2kanon** [comment]
@rakuten i have 1000, but trying send 9999. 
![image](https://user-images.githubusercontent.com/60179867/74010310-8c0a6600-49c8-11ea-9e7d-759231fdeea2.png)

**Comment by obasys** [comment]
@decryp2kanon Volbil will provide a list of all that errors, which I receive from API and I'll change it to understandable messages

**Comment by obasys** [comment]
![image](https://user-images.githubusercontent.com/17891656/74102720-ce5daf80-4b4e-11ea-8527-dadb4cf56d11.png)

@decryp2kanon errors to such representation, need some changes in API, to make it look better, so I've asked Volbil about that and ASAP he will change it, I'll do changes in message representation.

Maybe, for now, let it be like this one, it's pretty clear for us will be to bug fix errors

**Comment by decryp2kanon** [comment]
@obasys how long take fix this display issue? we have to release on 2020-02-14. is this possible? @volbil if we fix, we have to do ASAP

**Comment by obasys** [comment]
@decryp2kanon to my mind, that looks good enough and not smth like a bug, because we just represent an error, so I think it's possible to release an app as it is

**Comment by decryp2kanon** [comment]
@obasys i agreed to you. its fine. you can close this issue, if you OK.

**Comment by obasys** [comment]
@decryp2kanon can leave it as a feature, for future releases

**Comment by cryptozeny** [comment]
yeah great
