### ISSUE TITLE
The label text of the "Enter password" button should be "Unlock wallet" (or something else)

### ISSUE THREAD

**Issue by altbtm** [sugarchain-project/translation_android_wallet#49]
Tap one of the wallets on the start-up screen and you will be requested to enter the password into the "Enter password" field and press the "Enter password" button.

I think the label text of the button should be something else because you don't "enter" the password into the button.

I would suggest "Unlock wallet" or "Send". (Technically, the password is not sent to the blockchain, I prefer the former.)

Note: I'm using the version alpha.

![sugar_enter_password](https://user-images.githubusercontent.com/60621506/74014145-67ff5280-49d1-11ea-8295-524c7710988c.png)

**Comment by decryp2kanon** [comment]
yeah good suggestion. it looks duplicated.

![image](https://user-images.githubusercontent.com/60179867/74014819-cbd64b00-49d2-11ea-940e-21fa6690e3d6.png)

**Comment by obasys** [comment]
@decryp2kanon need everyone to change it in translation

**Comment by obasys** [comment]
@decryp2kanon  so everyone need to change this line

https://github.com/sugarchain-project/translation_android_wallet/commit/6a0beb0cd053f7bf639d17f661d6c1e8df248e5f

**Comment by obasys** [comment]
@decryp2kanon I'll close this issue, in case I've already fixed it, but need to overview changes in each lang file
