### ISSUE TITLE
The bottom of the Japanese descriptions with line-breaks on the setting tab are hidden

### ISSUE THREAD

**Issue by altbtm** [sugarchain-project/translation_android_wallet#50]
Please take a look at the attached screenshot. You see the bottoms of the Japanese characters in the 2nd row (line-broken) are hidden.

Note: The version of the app is alpha.

![2020-02-07 17 33 30](https://user-images.githubusercontent.com/60621506/74014752-a6e1d800-49d2-11ea-9724-9d91655daa0c.png)

**Comment by decryp2kanon** [comment]
good point!

**Comment by obasys** [comment]
@altbtm @decryp2kanon proposition is to rephrase that 2 sentences, because making buttons higher or cutting sentences is not a good solution

**Comment by obasys** [comment]
@altbtm so please, if you can, just rephrase it and that's all

**Comment by decryp2kanon** [comment]
@altbtm could you make shorter sentence? i understood, but it happened only in japanese. if you can make it shorter, we can reduce our work :sweat_smile:

**Comment by altbtm** [comment]
@obasys @decryp2kanon Sure. I'm working on reviewing the sentences now. Will push later.

**Comment by cryptozeny** [comment]
thanks!
