### ISSUE TITLE
The title and the cancel link on the Enter Password view should be displayed in the local language

### ISSUE THREAD

**Issue by altbtm** [sugarchain-project/translation_android_wallet#52]
This is a screenshot of the version alpha taken on the Japanese android. The title (top-right) and the Cancel link (top-left) should be in Japanese but actually both of them are in English.

![2020-02-07 17 32 46](https://user-images.githubusercontent.com/60621506/74015173-78b0c800-49d3-11ea-91a7-fafe38218bd1.png)

**Comment by decryp2kanon** [comment]
yeah some items are not tralslated.

**Comment by obasys** [comment]
> yeah some items are not tralslated.

provide more items where we have this issue

**Comment by obasys** [comment]
Fixed everything, will update in new apk
