### ISSUE TITLE
layout broken if i back from explorer(chrome)

### ISSUE THREAD

**Issue by decryp2kanon** [sugarchain-project/translation_android_wallet#58]
![image](https://user-images.githubusercontent.com/60179867/74104561-52d52000-4b99-11ea-89ac-f369b19d8c1e.png)

it was normal, but its layout broken, when i use back button on explorer (chrome)

**Comment by decryp2kanon** [comment]
damn, i cannot reproduce lol it should ask me the password, but this time it didnt ask me. and layout broken. :thinking:  i guess its just some conflict with old one? but i am sure, i deleted old version.

**Comment by obasys** [comment]
@decryp2kanon yeah, seems that's some conflict with the older version, so will close this issue for now
